// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/request/RecoveryDNMsgReq.proto

package com.txtech.services.protobuf.request;

public final class RecoveryDNMsgProtoReq {
  private RecoveryDNMsgProtoReq() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RecoveryDNMsgReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.request.RecoveryDNMsgReq)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code protobuf.request.RecoveryDNMsgReq}
   */
  public  static final class RecoveryDNMsgReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.request.RecoveryDNMsgReq)
      RecoveryDNMsgReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RecoveryDNMsgReq.newBuilder() to construct.
    private RecoveryDNMsgReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RecoveryDNMsgReq() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RecoveryDNMsgReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.internal_static_protobuf_request_RecoveryDNMsgReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.internal_static_protobuf_request_RecoveryDNMsgReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq.class, com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq)) {
        return super.equals(obj);
      }
      com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq other = (com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.request.RecoveryDNMsgReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.request.RecoveryDNMsgReq)
        com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.internal_static_protobuf_request_RecoveryDNMsgReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.internal_static_protobuf_request_RecoveryDNMsgReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq.class, com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq.Builder.class);
      }

      // Construct using com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.internal_static_protobuf_request_RecoveryDNMsgReq_descriptor;
      }

      @java.lang.Override
      public com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq getDefaultInstanceForType() {
        return com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq build() {
        com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq buildPartial() {
        com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq result = new com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq) {
          return mergeFrom((com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq other) {
        if (other == com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.request.RecoveryDNMsgReq)
    }

    // @@protoc_insertion_point(class_scope:protobuf.request.RecoveryDNMsgReq)
    private static final com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq();
    }

    public static com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<RecoveryDNMsgReq>
        PARSER = new com.google.protobuf.AbstractParser<RecoveryDNMsgReq>() {
      @java.lang.Override
      public RecoveryDNMsgReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RecoveryDNMsgReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RecoveryDNMsgReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RecoveryDNMsgReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.txtech.services.protobuf.request.RecoveryDNMsgProtoReq.RecoveryDNMsgReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_request_RecoveryDNMsgReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_request_RecoveryDNMsgReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'protobuf/request/RecoveryDNMsgReq.prot" +
      "o\022\020protobuf.request\"\022\n\020RecoveryDNMsgReqB" +
      "=\n$com.txtech.services.protobuf.requestB" +
      "\025RecoveryDNMsgProtoReq"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_request_RecoveryDNMsgReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_request_RecoveryDNMsgReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_request_RecoveryDNMsgReq_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
