// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/request/transactionHistoryRequest.proto

package com.txtech.services.protobuf.request;

public final class TransactionHistoryRequestProtos {
  private TransactionHistoryRequestProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TransactionHistoryRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.request.TransactionHistoryRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string clientID = 1;</code>
     */
    boolean hasClientID();
    /**
     * <code>required string clientID = 1;</code>
     */
    java.lang.String getClientID();
    /**
     * <code>required string clientID = 1;</code>
     */
    com.google.protobuf.ByteString
        getClientIDBytes();

    /**
     * <code>required int32 trandingAccSeq = 2;</code>
     */
    boolean hasTrandingAccSeq();
    /**
     * <code>required int32 trandingAccSeq = 2;</code>
     */
    int getTrandingAccSeq();

    /**
     * <code>required string subAccSeq = 3;</code>
     */
    boolean hasSubAccSeq();
    /**
     * <code>required string subAccSeq = 3;</code>
     */
    java.lang.String getSubAccSeq();
    /**
     * <code>required string subAccSeq = 3;</code>
     */
    com.google.protobuf.ByteString
        getSubAccSeqBytes();

    /**
     * <code>required string language = 4;</code>
     */
    boolean hasLanguage();
    /**
     * <code>required string language = 4;</code>
     */
    java.lang.String getLanguage();
    /**
     * <code>required string language = 4;</code>
     */
    com.google.protobuf.ByteString
        getLanguageBytes();

    /**
     * <code>required string fromDate = 5;</code>
     */
    boolean hasFromDate();
    /**
     * <code>required string fromDate = 5;</code>
     */
    java.lang.String getFromDate();
    /**
     * <code>required string fromDate = 5;</code>
     */
    com.google.protobuf.ByteString
        getFromDateBytes();

    /**
     * <code>required string toDate = 6;</code>
     */
    boolean hasToDate();
    /**
     * <code>required string toDate = 6;</code>
     */
    java.lang.String getToDate();
    /**
     * <code>required string toDate = 6;</code>
     */
    com.google.protobuf.ByteString
        getToDateBytes();

    /**
     * <code>required string tranType = 7;</code>
     */
    boolean hasTranType();
    /**
     * <code>required string tranType = 7;</code>
     */
    java.lang.String getTranType();
    /**
     * <code>required string tranType = 7;</code>
     */
    com.google.protobuf.ByteString
        getTranTypeBytes();
  }
  /**
   * Protobuf type {@code protobuf.request.TransactionHistoryRequest}
   */
  public  static final class TransactionHistoryRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.request.TransactionHistoryRequest)
      TransactionHistoryRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TransactionHistoryRequest.newBuilder() to construct.
    private TransactionHistoryRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransactionHistoryRequest() {
      clientID_ = "";
      subAccSeq_ = "";
      language_ = "";
      fromDate_ = "";
      toDate_ = "";
      tranType_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TransactionHistoryRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              clientID_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              trandingAccSeq_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              subAccSeq_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              language_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              fromDate_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              toDate_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              tranType_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.internal_static_protobuf_request_TransactionHistoryRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.internal_static_protobuf_request_TransactionHistoryRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest.class, com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest.Builder.class);
    }

    private int bitField0_;
    public static final int CLIENTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object clientID_;
    /**
     * <code>required string clientID = 1;</code>
     */
    public boolean hasClientID() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string clientID = 1;</code>
     */
    public java.lang.String getClientID() {
      java.lang.Object ref = clientID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clientID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string clientID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClientIDBytes() {
      java.lang.Object ref = clientID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRANDINGACCSEQ_FIELD_NUMBER = 2;
    private int trandingAccSeq_;
    /**
     * <code>required int32 trandingAccSeq = 2;</code>
     */
    public boolean hasTrandingAccSeq() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 trandingAccSeq = 2;</code>
     */
    public int getTrandingAccSeq() {
      return trandingAccSeq_;
    }

    public static final int SUBACCSEQ_FIELD_NUMBER = 3;
    private volatile java.lang.Object subAccSeq_;
    /**
     * <code>required string subAccSeq = 3;</code>
     */
    public boolean hasSubAccSeq() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string subAccSeq = 3;</code>
     */
    public java.lang.String getSubAccSeq() {
      java.lang.Object ref = subAccSeq_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          subAccSeq_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string subAccSeq = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSubAccSeqBytes() {
      java.lang.Object ref = subAccSeq_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subAccSeq_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LANGUAGE_FIELD_NUMBER = 4;
    private volatile java.lang.Object language_;
    /**
     * <code>required string language = 4;</code>
     */
    public boolean hasLanguage() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required string language = 4;</code>
     */
    public java.lang.String getLanguage() {
      java.lang.Object ref = language_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          language_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string language = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLanguageBytes() {
      java.lang.Object ref = language_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        language_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROMDATE_FIELD_NUMBER = 5;
    private volatile java.lang.Object fromDate_;
    /**
     * <code>required string fromDate = 5;</code>
     */
    public boolean hasFromDate() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required string fromDate = 5;</code>
     */
    public java.lang.String getFromDate() {
      java.lang.Object ref = fromDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fromDate_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string fromDate = 5;</code>
     */
    public com.google.protobuf.ByteString
        getFromDateBytes() {
      java.lang.Object ref = fromDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TODATE_FIELD_NUMBER = 6;
    private volatile java.lang.Object toDate_;
    /**
     * <code>required string toDate = 6;</code>
     */
    public boolean hasToDate() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required string toDate = 6;</code>
     */
    public java.lang.String getToDate() {
      java.lang.Object ref = toDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          toDate_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string toDate = 6;</code>
     */
    public com.google.protobuf.ByteString
        getToDateBytes() {
      java.lang.Object ref = toDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRANTYPE_FIELD_NUMBER = 7;
    private volatile java.lang.Object tranType_;
    /**
     * <code>required string tranType = 7;</code>
     */
    public boolean hasTranType() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>required string tranType = 7;</code>
     */
    public java.lang.String getTranType() {
      java.lang.Object ref = tranType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tranType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string tranType = 7;</code>
     */
    public com.google.protobuf.ByteString
        getTranTypeBytes() {
      java.lang.Object ref = tranType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tranType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasClientID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTrandingAccSeq()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSubAccSeq()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLanguage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFromDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTranType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientID_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, trandingAccSeq_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, subAccSeq_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, language_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, fromDate_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, toDate_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, tranType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientID_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, trandingAccSeq_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, subAccSeq_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, language_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, fromDate_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, toDate_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, tranType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest)) {
        return super.equals(obj);
      }
      com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest other = (com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest) obj;

      if (hasClientID() != other.hasClientID()) return false;
      if (hasClientID()) {
        if (!getClientID()
            .equals(other.getClientID())) return false;
      }
      if (hasTrandingAccSeq() != other.hasTrandingAccSeq()) return false;
      if (hasTrandingAccSeq()) {
        if (getTrandingAccSeq()
            != other.getTrandingAccSeq()) return false;
      }
      if (hasSubAccSeq() != other.hasSubAccSeq()) return false;
      if (hasSubAccSeq()) {
        if (!getSubAccSeq()
            .equals(other.getSubAccSeq())) return false;
      }
      if (hasLanguage() != other.hasLanguage()) return false;
      if (hasLanguage()) {
        if (!getLanguage()
            .equals(other.getLanguage())) return false;
      }
      if (hasFromDate() != other.hasFromDate()) return false;
      if (hasFromDate()) {
        if (!getFromDate()
            .equals(other.getFromDate())) return false;
      }
      if (hasToDate() != other.hasToDate()) return false;
      if (hasToDate()) {
        if (!getToDate()
            .equals(other.getToDate())) return false;
      }
      if (hasTranType() != other.hasTranType()) return false;
      if (hasTranType()) {
        if (!getTranType()
            .equals(other.getTranType())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasClientID()) {
        hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
        hash = (53 * hash) + getClientID().hashCode();
      }
      if (hasTrandingAccSeq()) {
        hash = (37 * hash) + TRANDINGACCSEQ_FIELD_NUMBER;
        hash = (53 * hash) + getTrandingAccSeq();
      }
      if (hasSubAccSeq()) {
        hash = (37 * hash) + SUBACCSEQ_FIELD_NUMBER;
        hash = (53 * hash) + getSubAccSeq().hashCode();
      }
      if (hasLanguage()) {
        hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
        hash = (53 * hash) + getLanguage().hashCode();
      }
      if (hasFromDate()) {
        hash = (37 * hash) + FROMDATE_FIELD_NUMBER;
        hash = (53 * hash) + getFromDate().hashCode();
      }
      if (hasToDate()) {
        hash = (37 * hash) + TODATE_FIELD_NUMBER;
        hash = (53 * hash) + getToDate().hashCode();
      }
      if (hasTranType()) {
        hash = (37 * hash) + TRANTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getTranType().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.request.TransactionHistoryRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.request.TransactionHistoryRequest)
        com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.internal_static_protobuf_request_TransactionHistoryRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.internal_static_protobuf_request_TransactionHistoryRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest.class, com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest.Builder.class);
      }

      // Construct using com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        clientID_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        trandingAccSeq_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        subAccSeq_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        language_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        fromDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        toDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        tranType_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.internal_static_protobuf_request_TransactionHistoryRequest_descriptor;
      }

      @java.lang.Override
      public com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest getDefaultInstanceForType() {
        return com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest build() {
        com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest buildPartial() {
        com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest result = new com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.clientID_ = clientID_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.trandingAccSeq_ = trandingAccSeq_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.subAccSeq_ = subAccSeq_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.language_ = language_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.fromDate_ = fromDate_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.toDate_ = toDate_;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          to_bitField0_ |= 0x00000040;
        }
        result.tranType_ = tranType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest) {
          return mergeFrom((com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest other) {
        if (other == com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest.getDefaultInstance()) return this;
        if (other.hasClientID()) {
          bitField0_ |= 0x00000001;
          clientID_ = other.clientID_;
          onChanged();
        }
        if (other.hasTrandingAccSeq()) {
          setTrandingAccSeq(other.getTrandingAccSeq());
        }
        if (other.hasSubAccSeq()) {
          bitField0_ |= 0x00000004;
          subAccSeq_ = other.subAccSeq_;
          onChanged();
        }
        if (other.hasLanguage()) {
          bitField0_ |= 0x00000008;
          language_ = other.language_;
          onChanged();
        }
        if (other.hasFromDate()) {
          bitField0_ |= 0x00000010;
          fromDate_ = other.fromDate_;
          onChanged();
        }
        if (other.hasToDate()) {
          bitField0_ |= 0x00000020;
          toDate_ = other.toDate_;
          onChanged();
        }
        if (other.hasTranType()) {
          bitField0_ |= 0x00000040;
          tranType_ = other.tranType_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasClientID()) {
          return false;
        }
        if (!hasTrandingAccSeq()) {
          return false;
        }
        if (!hasSubAccSeq()) {
          return false;
        }
        if (!hasLanguage()) {
          return false;
        }
        if (!hasFromDate()) {
          return false;
        }
        if (!hasToDate()) {
          return false;
        }
        if (!hasTranType()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object clientID_ = "";
      /**
       * <code>required string clientID = 1;</code>
       */
      public boolean hasClientID() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string clientID = 1;</code>
       */
      public java.lang.String getClientID() {
        java.lang.Object ref = clientID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            clientID_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string clientID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getClientIDBytes() {
        java.lang.Object ref = clientID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string clientID = 1;</code>
       */
      public Builder setClientID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        clientID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string clientID = 1;</code>
       */
      public Builder clearClientID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clientID_ = getDefaultInstance().getClientID();
        onChanged();
        return this;
      }
      /**
       * <code>required string clientID = 1;</code>
       */
      public Builder setClientIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        clientID_ = value;
        onChanged();
        return this;
      }

      private int trandingAccSeq_ ;
      /**
       * <code>required int32 trandingAccSeq = 2;</code>
       */
      public boolean hasTrandingAccSeq() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 trandingAccSeq = 2;</code>
       */
      public int getTrandingAccSeq() {
        return trandingAccSeq_;
      }
      /**
       * <code>required int32 trandingAccSeq = 2;</code>
       */
      public Builder setTrandingAccSeq(int value) {
        bitField0_ |= 0x00000002;
        trandingAccSeq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 trandingAccSeq = 2;</code>
       */
      public Builder clearTrandingAccSeq() {
        bitField0_ = (bitField0_ & ~0x00000002);
        trandingAccSeq_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object subAccSeq_ = "";
      /**
       * <code>required string subAccSeq = 3;</code>
       */
      public boolean hasSubAccSeq() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required string subAccSeq = 3;</code>
       */
      public java.lang.String getSubAccSeq() {
        java.lang.Object ref = subAccSeq_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            subAccSeq_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string subAccSeq = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSubAccSeqBytes() {
        java.lang.Object ref = subAccSeq_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subAccSeq_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string subAccSeq = 3;</code>
       */
      public Builder setSubAccSeq(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        subAccSeq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string subAccSeq = 3;</code>
       */
      public Builder clearSubAccSeq() {
        bitField0_ = (bitField0_ & ~0x00000004);
        subAccSeq_ = getDefaultInstance().getSubAccSeq();
        onChanged();
        return this;
      }
      /**
       * <code>required string subAccSeq = 3;</code>
       */
      public Builder setSubAccSeqBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        subAccSeq_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object language_ = "";
      /**
       * <code>required string language = 4;</code>
       */
      public boolean hasLanguage() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required string language = 4;</code>
       */
      public java.lang.String getLanguage() {
        java.lang.Object ref = language_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            language_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string language = 4;</code>
       */
      public com.google.protobuf.ByteString
          getLanguageBytes() {
        java.lang.Object ref = language_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          language_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string language = 4;</code>
       */
      public Builder setLanguage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        language_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string language = 4;</code>
       */
      public Builder clearLanguage() {
        bitField0_ = (bitField0_ & ~0x00000008);
        language_ = getDefaultInstance().getLanguage();
        onChanged();
        return this;
      }
      /**
       * <code>required string language = 4;</code>
       */
      public Builder setLanguageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        language_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object fromDate_ = "";
      /**
       * <code>required string fromDate = 5;</code>
       */
      public boolean hasFromDate() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required string fromDate = 5;</code>
       */
      public java.lang.String getFromDate() {
        java.lang.Object ref = fromDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fromDate_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string fromDate = 5;</code>
       */
      public com.google.protobuf.ByteString
          getFromDateBytes() {
        java.lang.Object ref = fromDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string fromDate = 5;</code>
       */
      public Builder setFromDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        fromDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string fromDate = 5;</code>
       */
      public Builder clearFromDate() {
        bitField0_ = (bitField0_ & ~0x00000010);
        fromDate_ = getDefaultInstance().getFromDate();
        onChanged();
        return this;
      }
      /**
       * <code>required string fromDate = 5;</code>
       */
      public Builder setFromDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        fromDate_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object toDate_ = "";
      /**
       * <code>required string toDate = 6;</code>
       */
      public boolean hasToDate() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>required string toDate = 6;</code>
       */
      public java.lang.String getToDate() {
        java.lang.Object ref = toDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            toDate_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string toDate = 6;</code>
       */
      public com.google.protobuf.ByteString
          getToDateBytes() {
        java.lang.Object ref = toDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string toDate = 6;</code>
       */
      public Builder setToDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        toDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string toDate = 6;</code>
       */
      public Builder clearToDate() {
        bitField0_ = (bitField0_ & ~0x00000020);
        toDate_ = getDefaultInstance().getToDate();
        onChanged();
        return this;
      }
      /**
       * <code>required string toDate = 6;</code>
       */
      public Builder setToDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        toDate_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tranType_ = "";
      /**
       * <code>required string tranType = 7;</code>
       */
      public boolean hasTranType() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>required string tranType = 7;</code>
       */
      public java.lang.String getTranType() {
        java.lang.Object ref = tranType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            tranType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string tranType = 7;</code>
       */
      public com.google.protobuf.ByteString
          getTranTypeBytes() {
        java.lang.Object ref = tranType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tranType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string tranType = 7;</code>
       */
      public Builder setTranType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        tranType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string tranType = 7;</code>
       */
      public Builder clearTranType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        tranType_ = getDefaultInstance().getTranType();
        onChanged();
        return this;
      }
      /**
       * <code>required string tranType = 7;</code>
       */
      public Builder setTranTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        tranType_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.request.TransactionHistoryRequest)
    }

    // @@protoc_insertion_point(class_scope:protobuf.request.TransactionHistoryRequest)
    private static final com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest();
    }

    public static com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TransactionHistoryRequest>
        PARSER = new com.google.protobuf.AbstractParser<TransactionHistoryRequest>() {
      @java.lang.Override
      public TransactionHistoryRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransactionHistoryRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TransactionHistoryRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransactionHistoryRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.txtech.services.protobuf.request.TransactionHistoryRequestProtos.TransactionHistoryRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_request_TransactionHistoryRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_request_TransactionHistoryRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0protobuf/request/transactionHistoryReq" +
      "uest.proto\022\020protobuf.request\"\236\001\n\031Transac" +
      "tionHistoryRequest\022\020\n\010clientID\030\001 \002(\t\022\026\n\016" +
      "trandingAccSeq\030\002 \002(\005\022\021\n\tsubAccSeq\030\003 \002(\t\022" +
      "\020\n\010language\030\004 \002(\t\022\020\n\010fromDate\030\005 \002(\t\022\016\n\006t" +
      "oDate\030\006 \002(\t\022\020\n\010tranType\030\007 \002(\tBG\n$com.txt" +
      "ech.services.protobuf.requestB\037Transacti" +
      "onHistoryRequestProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_request_TransactionHistoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_request_TransactionHistoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_request_TransactionHistoryRequest_descriptor,
        new java.lang.String[] { "ClientID", "TrandingAccSeq", "SubAccSeq", "Language", "FromDate", "ToDate", "TranType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
