// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/response/orderEnquiryResponse.proto

package com.txtech.services.protobuf.response;

public final class OrderEnquiryResponseProtos {
  private OrderEnquiryResponseProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OrderEnquiryResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.response.OrderEnquiryResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 msgSeq = 1;</code>
     */
    boolean hasMsgSeq();
    /**
     * <code>optional int32 msgSeq = 1;</code>
     */
    int getMsgSeq();

    /**
     * <code>optional string errorCode = 2;</code>
     */
    boolean hasErrorCode();
    /**
     * <code>optional string errorCode = 2;</code>
     */
    java.lang.String getErrorCode();
    /**
     * <code>optional string errorCode = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrorCodeBytes();

    /**
     * <code>optional string errorMessage = 3;</code>
     */
    boolean hasErrorMessage();
    /**
     * <code>optional string errorMessage = 3;</code>
     */
    java.lang.String getErrorMessage();
    /**
     * <code>optional string errorMessage = 3;</code>
     */
    com.google.protobuf.ByteString
        getErrorMessageBytes();

    /**
     * <code>optional string messageID = 4;</code>
     */
    boolean hasMessageID();
    /**
     * <code>optional string messageID = 4;</code>
     */
    java.lang.String getMessageID();
    /**
     * <code>optional string messageID = 4;</code>
     */
    com.google.protobuf.ByteString
        getMessageIDBytes();

    /**
     * <code>optional int32 returnCode = 5;</code>
     */
    boolean hasReturnCode();
    /**
     * <code>optional int32 returnCode = 5;</code>
     */
    int getReturnCode();

    /**
     * <code>repeated .protobuf.bean.OrderDetail orderEnquiryInfoList = 6;</code>
     */
    java.util.List<com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetail> 
        getOrderEnquiryInfoListList();
    /**
     * <code>repeated .protobuf.bean.OrderDetail orderEnquiryInfoList = 6;</code>
     */
    com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetail getOrderEnquiryInfoList(int index);
    /**
     * <code>repeated .protobuf.bean.OrderDetail orderEnquiryInfoList = 6;</code>
     */
    int getOrderEnquiryInfoListCount();
    /**
     * <code>repeated .protobuf.bean.OrderDetail orderEnquiryInfoList = 6;</code>
     */
    java.util.List<? extends com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetailOrBuilder> 
        getOrderEnquiryInfoListOrBuilderList();
    /**
     * <code>repeated .protobuf.bean.OrderDetail orderEnquiryInfoList = 6;</code>
     */
    com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetailOrBuilder getOrderEnquiryInfoListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protobuf.response.OrderEnquiryResponse}
   */
  public  static final class OrderEnquiryResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.response.OrderEnquiryResponse)
      OrderEnquiryResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OrderEnquiryResponse.newBuilder() to construct.
    private OrderEnquiryResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OrderEnquiryResponse() {
      errorCode_ = "";
      errorMessage_ = "";
      messageID_ = "";
      orderEnquiryInfoList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OrderEnquiryResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              msgSeq_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              errorCode_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              errorMessage_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              messageID_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              returnCode_ = input.readInt32();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) != 0)) {
                orderEnquiryInfoList_ = new java.util.ArrayList<com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetail>();
                mutable_bitField0_ |= 0x00000020;
              }
              orderEnquiryInfoList_.add(
                  input.readMessage(com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetail.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) != 0)) {
          orderEnquiryInfoList_ = java.util.Collections.unmodifiableList(orderEnquiryInfoList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.internal_static_protobuf_response_OrderEnquiryResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.internal_static_protobuf_response_OrderEnquiryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse.class, com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse.Builder.class);
    }

    private int bitField0_;
    public static final int MSGSEQ_FIELD_NUMBER = 1;
    private int msgSeq_;
    /**
     * <code>optional int32 msgSeq = 1;</code>
     */
    public boolean hasMsgSeq() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 msgSeq = 1;</code>
     */
    public int getMsgSeq() {
      return msgSeq_;
    }

    public static final int ERRORCODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object errorCode_;
    /**
     * <code>optional string errorCode = 2;</code>
     */
    public boolean hasErrorCode() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string errorCode = 2;</code>
     */
    public java.lang.String getErrorCode() {
      java.lang.Object ref = errorCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string errorCode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrorCodeBytes() {
      java.lang.Object ref = errorCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRORMESSAGE_FIELD_NUMBER = 3;
    private volatile java.lang.Object errorMessage_;
    /**
     * <code>optional string errorMessage = 3;</code>
     */
    public boolean hasErrorMessage() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string errorMessage = 3;</code>
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorMessage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string errorMessage = 3;</code>
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGEID_FIELD_NUMBER = 4;
    private volatile java.lang.Object messageID_;
    /**
     * <code>optional string messageID = 4;</code>
     */
    public boolean hasMessageID() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string messageID = 4;</code>
     */
    public java.lang.String getMessageID() {
      java.lang.Object ref = messageID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          messageID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string messageID = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMessageIDBytes() {
      java.lang.Object ref = messageID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RETURNCODE_FIELD_NUMBER = 5;
    private int returnCode_;
    /**
     * <code>optional int32 returnCode = 5;</code>
     */
    public boolean hasReturnCode() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 returnCode = 5;</code>
     */
    public int getReturnCode() {
      return returnCode_;
    }

    public static final int ORDERENQUIRYINFOLIST_FIELD_NUMBER = 6;
    private java.util.List<com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetail> orderEnquiryInfoList_;
    /**
     * <code>repeated .protobuf.bean.OrderDetail orderEnquiryInfoList = 6;</code>
     */
    public java.util.List<com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetail> getOrderEnquiryInfoListList() {
      return orderEnquiryInfoList_;
    }
    /**
     * <code>repeated .protobuf.bean.OrderDetail orderEnquiryInfoList = 6;</code>
     */
    public java.util.List<? extends com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetailOrBuilder> 
        getOrderEnquiryInfoListOrBuilderList() {
      return orderEnquiryInfoList_;
    }
    /**
     * <code>repeated .protobuf.bean.OrderDetail orderEnquiryInfoList = 6;</code>
     */
    public int getOrderEnquiryInfoListCount() {
      return orderEnquiryInfoList_.size();
    }
    /**
     * <code>repeated .protobuf.bean.OrderDetail orderEnquiryInfoList = 6;</code>
     */
    public com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetail getOrderEnquiryInfoList(int index) {
      return orderEnquiryInfoList_.get(index);
    }
    /**
     * <code>repeated .protobuf.bean.OrderDetail orderEnquiryInfoList = 6;</code>
     */
    public com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetailOrBuilder getOrderEnquiryInfoListOrBuilder(
        int index) {
      return orderEnquiryInfoList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, msgSeq_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errorCode_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errorMessage_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, messageID_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(5, returnCode_);
      }
      for (int i = 0; i < orderEnquiryInfoList_.size(); i++) {
        output.writeMessage(6, orderEnquiryInfoList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgSeq_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errorCode_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, errorMessage_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, messageID_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, returnCode_);
      }
      for (int i = 0; i < orderEnquiryInfoList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, orderEnquiryInfoList_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse)) {
        return super.equals(obj);
      }
      com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse other = (com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse) obj;

      if (hasMsgSeq() != other.hasMsgSeq()) return false;
      if (hasMsgSeq()) {
        if (getMsgSeq()
            != other.getMsgSeq()) return false;
      }
      if (hasErrorCode() != other.hasErrorCode()) return false;
      if (hasErrorCode()) {
        if (!getErrorCode()
            .equals(other.getErrorCode())) return false;
      }
      if (hasErrorMessage() != other.hasErrorMessage()) return false;
      if (hasErrorMessage()) {
        if (!getErrorMessage()
            .equals(other.getErrorMessage())) return false;
      }
      if (hasMessageID() != other.hasMessageID()) return false;
      if (hasMessageID()) {
        if (!getMessageID()
            .equals(other.getMessageID())) return false;
      }
      if (hasReturnCode() != other.hasReturnCode()) return false;
      if (hasReturnCode()) {
        if (getReturnCode()
            != other.getReturnCode()) return false;
      }
      if (!getOrderEnquiryInfoListList()
          .equals(other.getOrderEnquiryInfoListList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMsgSeq()) {
        hash = (37 * hash) + MSGSEQ_FIELD_NUMBER;
        hash = (53 * hash) + getMsgSeq();
      }
      if (hasErrorCode()) {
        hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
        hash = (53 * hash) + getErrorCode().hashCode();
      }
      if (hasErrorMessage()) {
        hash = (37 * hash) + ERRORMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getErrorMessage().hashCode();
      }
      if (hasMessageID()) {
        hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
        hash = (53 * hash) + getMessageID().hashCode();
      }
      if (hasReturnCode()) {
        hash = (37 * hash) + RETURNCODE_FIELD_NUMBER;
        hash = (53 * hash) + getReturnCode();
      }
      if (getOrderEnquiryInfoListCount() > 0) {
        hash = (37 * hash) + ORDERENQUIRYINFOLIST_FIELD_NUMBER;
        hash = (53 * hash) + getOrderEnquiryInfoListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.response.OrderEnquiryResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.response.OrderEnquiryResponse)
        com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.internal_static_protobuf_response_OrderEnquiryResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.internal_static_protobuf_response_OrderEnquiryResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse.class, com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse.Builder.class);
      }

      // Construct using com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getOrderEnquiryInfoListFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        msgSeq_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        errorCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        errorMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        messageID_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        returnCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (orderEnquiryInfoListBuilder_ == null) {
          orderEnquiryInfoList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          orderEnquiryInfoListBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.internal_static_protobuf_response_OrderEnquiryResponse_descriptor;
      }

      @java.lang.Override
      public com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse getDefaultInstanceForType() {
        return com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse build() {
        com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse buildPartial() {
        com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse result = new com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.msgSeq_ = msgSeq_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errorCode_ = errorCode_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.errorMessage_ = errorMessage_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.messageID_ = messageID_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.returnCode_ = returnCode_;
          to_bitField0_ |= 0x00000010;
        }
        if (orderEnquiryInfoListBuilder_ == null) {
          if (((bitField0_ & 0x00000020) != 0)) {
            orderEnquiryInfoList_ = java.util.Collections.unmodifiableList(orderEnquiryInfoList_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.orderEnquiryInfoList_ = orderEnquiryInfoList_;
        } else {
          result.orderEnquiryInfoList_ = orderEnquiryInfoListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse) {
          return mergeFrom((com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse other) {
        if (other == com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse.getDefaultInstance()) return this;
        if (other.hasMsgSeq()) {
          setMsgSeq(other.getMsgSeq());
        }
        if (other.hasErrorCode()) {
          bitField0_ |= 0x00000002;
          errorCode_ = other.errorCode_;
          onChanged();
        }
        if (other.hasErrorMessage()) {
          bitField0_ |= 0x00000004;
          errorMessage_ = other.errorMessage_;
          onChanged();
        }
        if (other.hasMessageID()) {
          bitField0_ |= 0x00000008;
          messageID_ = other.messageID_;
          onChanged();
        }
        if (other.hasReturnCode()) {
          setReturnCode(other.getReturnCode());
        }
        if (orderEnquiryInfoListBuilder_ == null) {
          if (!other.orderEnquiryInfoList_.isEmpty()) {
            if (orderEnquiryInfoList_.isEmpty()) {
              orderEnquiryInfoList_ = other.orderEnquiryInfoList_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureOrderEnquiryInfoListIsMutable();
              orderEnquiryInfoList_.addAll(other.orderEnquiryInfoList_);
            }
            onChanged();
          }
        } else {
          if (!other.orderEnquiryInfoList_.isEmpty()) {
            if (orderEnquiryInfoListBuilder_.isEmpty()) {
              orderEnquiryInfoListBuilder_.dispose();
              orderEnquiryInfoListBuilder_ = null;
              orderEnquiryInfoList_ = other.orderEnquiryInfoList_;
              bitField0_ = (bitField0_ & ~0x00000020);
              orderEnquiryInfoListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getOrderEnquiryInfoListFieldBuilder() : null;
            } else {
              orderEnquiryInfoListBuilder_.addAllMessages(other.orderEnquiryInfoList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int msgSeq_ ;
      /**
       * <code>optional int32 msgSeq = 1;</code>
       */
      public boolean hasMsgSeq() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 msgSeq = 1;</code>
       */
      public int getMsgSeq() {
        return msgSeq_;
      }
      /**
       * <code>optional int32 msgSeq = 1;</code>
       */
      public Builder setMsgSeq(int value) {
        bitField0_ |= 0x00000001;
        msgSeq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 msgSeq = 1;</code>
       */
      public Builder clearMsgSeq() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgSeq_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object errorCode_ = "";
      /**
       * <code>optional string errorCode = 2;</code>
       */
      public boolean hasErrorCode() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string errorCode = 2;</code>
       */
      public java.lang.String getErrorCode() {
        java.lang.Object ref = errorCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errorCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string errorCode = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrorCodeBytes() {
        java.lang.Object ref = errorCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errorCode = 2;</code>
       */
      public Builder setErrorCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorCode = 2;</code>
       */
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errorCode_ = getDefaultInstance().getErrorCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorCode = 2;</code>
       */
      public Builder setErrorCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errorCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object errorMessage_ = "";
      /**
       * <code>optional string errorMessage = 3;</code>
       */
      public boolean hasErrorMessage() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string errorMessage = 3;</code>
       */
      public java.lang.String getErrorMessage() {
        java.lang.Object ref = errorMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errorMessage_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string errorMessage = 3;</code>
       */
      public com.google.protobuf.ByteString
          getErrorMessageBytes() {
        java.lang.Object ref = errorMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errorMessage = 3;</code>
       */
      public Builder setErrorMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        errorMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorMessage = 3;</code>
       */
      public Builder clearErrorMessage() {
        bitField0_ = (bitField0_ & ~0x00000004);
        errorMessage_ = getDefaultInstance().getErrorMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorMessage = 3;</code>
       */
      public Builder setErrorMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        errorMessage_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object messageID_ = "";
      /**
       * <code>optional string messageID = 4;</code>
       */
      public boolean hasMessageID() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string messageID = 4;</code>
       */
      public java.lang.String getMessageID() {
        java.lang.Object ref = messageID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            messageID_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string messageID = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMessageIDBytes() {
        java.lang.Object ref = messageID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string messageID = 4;</code>
       */
      public Builder setMessageID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        messageID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string messageID = 4;</code>
       */
      public Builder clearMessageID() {
        bitField0_ = (bitField0_ & ~0x00000008);
        messageID_ = getDefaultInstance().getMessageID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string messageID = 4;</code>
       */
      public Builder setMessageIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        messageID_ = value;
        onChanged();
        return this;
      }

      private int returnCode_ ;
      /**
       * <code>optional int32 returnCode = 5;</code>
       */
      public boolean hasReturnCode() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional int32 returnCode = 5;</code>
       */
      public int getReturnCode() {
        return returnCode_;
      }
      /**
       * <code>optional int32 returnCode = 5;</code>
       */
      public Builder setReturnCode(int value) {
        bitField0_ |= 0x00000010;
        returnCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 returnCode = 5;</code>
       */
      public Builder clearReturnCode() {
        bitField0_ = (bitField0_ & ~0x00000010);
        returnCode_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetail> orderEnquiryInfoList_ =
        java.util.Collections.emptyList();
      private void ensureOrderEnquiryInfoListIsMutable() {
        if (!((bitField0_ & 0x00000020) != 0)) {
          orderEnquiryInfoList_ = new java.util.ArrayList<com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetail>(orderEnquiryInfoList_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetail, com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetail.Builder, com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetailOrBuilder> orderEnquiryInfoListBuilder_;

      /**
       * <code>repeated .protobuf.bean.OrderDetail orderEnquiryInfoList = 6;</code>
       */
      public java.util.List<com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetail> getOrderEnquiryInfoListList() {
        if (orderEnquiryInfoListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(orderEnquiryInfoList_);
        } else {
          return orderEnquiryInfoListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.bean.OrderDetail orderEnquiryInfoList = 6;</code>
       */
      public int getOrderEnquiryInfoListCount() {
        if (orderEnquiryInfoListBuilder_ == null) {
          return orderEnquiryInfoList_.size();
        } else {
          return orderEnquiryInfoListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.bean.OrderDetail orderEnquiryInfoList = 6;</code>
       */
      public com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetail getOrderEnquiryInfoList(int index) {
        if (orderEnquiryInfoListBuilder_ == null) {
          return orderEnquiryInfoList_.get(index);
        } else {
          return orderEnquiryInfoListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.bean.OrderDetail orderEnquiryInfoList = 6;</code>
       */
      public Builder setOrderEnquiryInfoList(
          int index, com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetail value) {
        if (orderEnquiryInfoListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrderEnquiryInfoListIsMutable();
          orderEnquiryInfoList_.set(index, value);
          onChanged();
        } else {
          orderEnquiryInfoListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.bean.OrderDetail orderEnquiryInfoList = 6;</code>
       */
      public Builder setOrderEnquiryInfoList(
          int index, com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetail.Builder builderForValue) {
        if (orderEnquiryInfoListBuilder_ == null) {
          ensureOrderEnquiryInfoListIsMutable();
          orderEnquiryInfoList_.set(index, builderForValue.build());
          onChanged();
        } else {
          orderEnquiryInfoListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.bean.OrderDetail orderEnquiryInfoList = 6;</code>
       */
      public Builder addOrderEnquiryInfoList(com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetail value) {
        if (orderEnquiryInfoListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrderEnquiryInfoListIsMutable();
          orderEnquiryInfoList_.add(value);
          onChanged();
        } else {
          orderEnquiryInfoListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.bean.OrderDetail orderEnquiryInfoList = 6;</code>
       */
      public Builder addOrderEnquiryInfoList(
          int index, com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetail value) {
        if (orderEnquiryInfoListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrderEnquiryInfoListIsMutable();
          orderEnquiryInfoList_.add(index, value);
          onChanged();
        } else {
          orderEnquiryInfoListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.bean.OrderDetail orderEnquiryInfoList = 6;</code>
       */
      public Builder addOrderEnquiryInfoList(
          com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetail.Builder builderForValue) {
        if (orderEnquiryInfoListBuilder_ == null) {
          ensureOrderEnquiryInfoListIsMutable();
          orderEnquiryInfoList_.add(builderForValue.build());
          onChanged();
        } else {
          orderEnquiryInfoListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.bean.OrderDetail orderEnquiryInfoList = 6;</code>
       */
      public Builder addOrderEnquiryInfoList(
          int index, com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetail.Builder builderForValue) {
        if (orderEnquiryInfoListBuilder_ == null) {
          ensureOrderEnquiryInfoListIsMutable();
          orderEnquiryInfoList_.add(index, builderForValue.build());
          onChanged();
        } else {
          orderEnquiryInfoListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.bean.OrderDetail orderEnquiryInfoList = 6;</code>
       */
      public Builder addAllOrderEnquiryInfoList(
          java.lang.Iterable<? extends com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetail> values) {
        if (orderEnquiryInfoListBuilder_ == null) {
          ensureOrderEnquiryInfoListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, orderEnquiryInfoList_);
          onChanged();
        } else {
          orderEnquiryInfoListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.bean.OrderDetail orderEnquiryInfoList = 6;</code>
       */
      public Builder clearOrderEnquiryInfoList() {
        if (orderEnquiryInfoListBuilder_ == null) {
          orderEnquiryInfoList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          orderEnquiryInfoListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.bean.OrderDetail orderEnquiryInfoList = 6;</code>
       */
      public Builder removeOrderEnquiryInfoList(int index) {
        if (orderEnquiryInfoListBuilder_ == null) {
          ensureOrderEnquiryInfoListIsMutable();
          orderEnquiryInfoList_.remove(index);
          onChanged();
        } else {
          orderEnquiryInfoListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.bean.OrderDetail orderEnquiryInfoList = 6;</code>
       */
      public com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetail.Builder getOrderEnquiryInfoListBuilder(
          int index) {
        return getOrderEnquiryInfoListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.bean.OrderDetail orderEnquiryInfoList = 6;</code>
       */
      public com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetailOrBuilder getOrderEnquiryInfoListOrBuilder(
          int index) {
        if (orderEnquiryInfoListBuilder_ == null) {
          return orderEnquiryInfoList_.get(index);  } else {
          return orderEnquiryInfoListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.bean.OrderDetail orderEnquiryInfoList = 6;</code>
       */
      public java.util.List<? extends com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetailOrBuilder> 
           getOrderEnquiryInfoListOrBuilderList() {
        if (orderEnquiryInfoListBuilder_ != null) {
          return orderEnquiryInfoListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(orderEnquiryInfoList_);
        }
      }
      /**
       * <code>repeated .protobuf.bean.OrderDetail orderEnquiryInfoList = 6;</code>
       */
      public com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetail.Builder addOrderEnquiryInfoListBuilder() {
        return getOrderEnquiryInfoListFieldBuilder().addBuilder(
            com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.bean.OrderDetail orderEnquiryInfoList = 6;</code>
       */
      public com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetail.Builder addOrderEnquiryInfoListBuilder(
          int index) {
        return getOrderEnquiryInfoListFieldBuilder().addBuilder(
            index, com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.bean.OrderDetail orderEnquiryInfoList = 6;</code>
       */
      public java.util.List<com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetail.Builder> 
           getOrderEnquiryInfoListBuilderList() {
        return getOrderEnquiryInfoListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetail, com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetail.Builder, com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetailOrBuilder> 
          getOrderEnquiryInfoListFieldBuilder() {
        if (orderEnquiryInfoListBuilder_ == null) {
          orderEnquiryInfoListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetail, com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetail.Builder, com.txtech.services.protobuf.bean.OrderDetailProtos.OrderDetailOrBuilder>(
                  orderEnquiryInfoList_,
                  ((bitField0_ & 0x00000020) != 0),
                  getParentForChildren(),
                  isClean());
          orderEnquiryInfoList_ = null;
        }
        return orderEnquiryInfoListBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.response.OrderEnquiryResponse)
    }

    // @@protoc_insertion_point(class_scope:protobuf.response.OrderEnquiryResponse)
    private static final com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse();
    }

    public static com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<OrderEnquiryResponse>
        PARSER = new com.google.protobuf.AbstractParser<OrderEnquiryResponse>() {
      @java.lang.Override
      public OrderEnquiryResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OrderEnquiryResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OrderEnquiryResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OrderEnquiryResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.txtech.services.protobuf.response.OrderEnquiryResponseProtos.OrderEnquiryResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_response_OrderEnquiryResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_response_OrderEnquiryResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,protobuf/response/orderEnquiryResponse" +
      ".proto\022\021protobuf.response\032\037protobuf/bean" +
      "/orderDetail.proto\"\260\001\n\024OrderEnquiryRespo" +
      "nse\022\016\n\006msgSeq\030\001 \001(\005\022\021\n\terrorCode\030\002 \001(\t\022\024" +
      "\n\014errorMessage\030\003 \001(\t\022\021\n\tmessageID\030\004 \001(\t\022" +
      "\022\n\nreturnCode\030\005 \001(\005\0228\n\024orderEnquiryInfoL" +
      "ist\030\006 \003(\0132\032.protobuf.bean.OrderDetailBC\n" +
      "%com.txtech.services.protobuf.responseB\032" +
      "OrderEnquiryResponseProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.txtech.services.protobuf.bean.OrderDetailProtos.getDescriptor(),
        }, assigner);
    internal_static_protobuf_response_OrderEnquiryResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_response_OrderEnquiryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_response_OrderEnquiryResponse_descriptor,
        new java.lang.String[] { "MsgSeq", "ErrorCode", "ErrorMessage", "MessageID", "ReturnCode", "OrderEnquiryInfoList", });
    com.txtech.services.protobuf.bean.OrderDetailProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
