// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/response/queryClientCashBalanceResponse.proto

package com.txtech.services.protobuf.response;

public final class QueryClientCashBalanceResponseProtos {
  private QueryClientCashBalanceResponseProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QueryClientCashBalanceResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.response.QueryClientCashBalanceResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 msgSeq = 1;</code>
     */
    boolean hasMsgSeq();
    /**
     * <code>optional int32 msgSeq = 1;</code>
     */
    int getMsgSeq();

    /**
     * <code>optional string errorCode = 2;</code>
     */
    boolean hasErrorCode();
    /**
     * <code>optional string errorCode = 2;</code>
     */
    java.lang.String getErrorCode();
    /**
     * <code>optional string errorCode = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrorCodeBytes();

    /**
     * <code>optional string errorMessage = 3;</code>
     */
    boolean hasErrorMessage();
    /**
     * <code>optional string errorMessage = 3;</code>
     */
    java.lang.String getErrorMessage();
    /**
     * <code>optional string errorMessage = 3;</code>
     */
    com.google.protobuf.ByteString
        getErrorMessageBytes();

    /**
     * <code>optional string messageID = 4;</code>
     */
    boolean hasMessageID();
    /**
     * <code>optional string messageID = 4;</code>
     */
    java.lang.String getMessageID();
    /**
     * <code>optional string messageID = 4;</code>
     */
    com.google.protobuf.ByteString
        getMessageIDBytes();

    /**
     * <code>optional int32 returnCode = 5;</code>
     */
    boolean hasReturnCode();
    /**
     * <code>optional int32 returnCode = 5;</code>
     */
    int getReturnCode();

    /**
     * <code>optional string name = 6;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 6;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 6;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string fullname = 7;</code>
     */
    boolean hasFullname();
    /**
     * <code>optional string fullname = 7;</code>
     */
    java.lang.String getFullname();
    /**
     * <code>optional string fullname = 7;</code>
     */
    com.google.protobuf.ByteString
        getFullnameBytes();

    /**
     * <code>repeated .protobuf.bean.AccountBalance accountBalanceInfo = 8;</code>
     */
    java.util.List<com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalance> 
        getAccountBalanceInfoList();
    /**
     * <code>repeated .protobuf.bean.AccountBalance accountBalanceInfo = 8;</code>
     */
    com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalance getAccountBalanceInfo(int index);
    /**
     * <code>repeated .protobuf.bean.AccountBalance accountBalanceInfo = 8;</code>
     */
    int getAccountBalanceInfoCount();
    /**
     * <code>repeated .protobuf.bean.AccountBalance accountBalanceInfo = 8;</code>
     */
    java.util.List<? extends com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalanceOrBuilder> 
        getAccountBalanceInfoOrBuilderList();
    /**
     * <code>repeated .protobuf.bean.AccountBalance accountBalanceInfo = 8;</code>
     */
    com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalanceOrBuilder getAccountBalanceInfoOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protobuf.response.QueryClientCashBalanceResponse}
   */
  public  static final class QueryClientCashBalanceResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.response.QueryClientCashBalanceResponse)
      QueryClientCashBalanceResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QueryClientCashBalanceResponse.newBuilder() to construct.
    private QueryClientCashBalanceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QueryClientCashBalanceResponse() {
      errorCode_ = "";
      errorMessage_ = "";
      messageID_ = "";
      name_ = "";
      fullname_ = "";
      accountBalanceInfo_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QueryClientCashBalanceResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              msgSeq_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              errorCode_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              errorMessage_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              messageID_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              returnCode_ = input.readInt32();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              name_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              fullname_ = bs;
              break;
            }
            case 66: {
              if (!((mutable_bitField0_ & 0x00000080) != 0)) {
                accountBalanceInfo_ = new java.util.ArrayList<com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalance>();
                mutable_bitField0_ |= 0x00000080;
              }
              accountBalanceInfo_.add(
                  input.readMessage(com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalance.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000080) != 0)) {
          accountBalanceInfo_ = java.util.Collections.unmodifiableList(accountBalanceInfo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.internal_static_protobuf_response_QueryClientCashBalanceResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.internal_static_protobuf_response_QueryClientCashBalanceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse.class, com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse.Builder.class);
    }

    private int bitField0_;
    public static final int MSGSEQ_FIELD_NUMBER = 1;
    private int msgSeq_;
    /**
     * <code>optional int32 msgSeq = 1;</code>
     */
    public boolean hasMsgSeq() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 msgSeq = 1;</code>
     */
    public int getMsgSeq() {
      return msgSeq_;
    }

    public static final int ERRORCODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object errorCode_;
    /**
     * <code>optional string errorCode = 2;</code>
     */
    public boolean hasErrorCode() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string errorCode = 2;</code>
     */
    public java.lang.String getErrorCode() {
      java.lang.Object ref = errorCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string errorCode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrorCodeBytes() {
      java.lang.Object ref = errorCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRORMESSAGE_FIELD_NUMBER = 3;
    private volatile java.lang.Object errorMessage_;
    /**
     * <code>optional string errorMessage = 3;</code>
     */
    public boolean hasErrorMessage() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string errorMessage = 3;</code>
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorMessage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string errorMessage = 3;</code>
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGEID_FIELD_NUMBER = 4;
    private volatile java.lang.Object messageID_;
    /**
     * <code>optional string messageID = 4;</code>
     */
    public boolean hasMessageID() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string messageID = 4;</code>
     */
    public java.lang.String getMessageID() {
      java.lang.Object ref = messageID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          messageID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string messageID = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMessageIDBytes() {
      java.lang.Object ref = messageID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RETURNCODE_FIELD_NUMBER = 5;
    private int returnCode_;
    /**
     * <code>optional int32 returnCode = 5;</code>
     */
    public boolean hasReturnCode() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 returnCode = 5;</code>
     */
    public int getReturnCode() {
      return returnCode_;
    }

    public static final int NAME_FIELD_NUMBER = 6;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 6;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string name = 6;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 6;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FULLNAME_FIELD_NUMBER = 7;
    private volatile java.lang.Object fullname_;
    /**
     * <code>optional string fullname = 7;</code>
     */
    public boolean hasFullname() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional string fullname = 7;</code>
     */
    public java.lang.String getFullname() {
      java.lang.Object ref = fullname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fullname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string fullname = 7;</code>
     */
    public com.google.protobuf.ByteString
        getFullnameBytes() {
      java.lang.Object ref = fullname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fullname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCOUNTBALANCEINFO_FIELD_NUMBER = 8;
    private java.util.List<com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalance> accountBalanceInfo_;
    /**
     * <code>repeated .protobuf.bean.AccountBalance accountBalanceInfo = 8;</code>
     */
    public java.util.List<com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalance> getAccountBalanceInfoList() {
      return accountBalanceInfo_;
    }
    /**
     * <code>repeated .protobuf.bean.AccountBalance accountBalanceInfo = 8;</code>
     */
    public java.util.List<? extends com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalanceOrBuilder> 
        getAccountBalanceInfoOrBuilderList() {
      return accountBalanceInfo_;
    }
    /**
     * <code>repeated .protobuf.bean.AccountBalance accountBalanceInfo = 8;</code>
     */
    public int getAccountBalanceInfoCount() {
      return accountBalanceInfo_.size();
    }
    /**
     * <code>repeated .protobuf.bean.AccountBalance accountBalanceInfo = 8;</code>
     */
    public com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalance getAccountBalanceInfo(int index) {
      return accountBalanceInfo_.get(index);
    }
    /**
     * <code>repeated .protobuf.bean.AccountBalance accountBalanceInfo = 8;</code>
     */
    public com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalanceOrBuilder getAccountBalanceInfoOrBuilder(
        int index) {
      return accountBalanceInfo_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, msgSeq_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errorCode_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errorMessage_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, messageID_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(5, returnCode_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, name_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, fullname_);
      }
      for (int i = 0; i < accountBalanceInfo_.size(); i++) {
        output.writeMessage(8, accountBalanceInfo_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgSeq_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errorCode_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, errorMessage_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, messageID_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, returnCode_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, name_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, fullname_);
      }
      for (int i = 0; i < accountBalanceInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, accountBalanceInfo_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse)) {
        return super.equals(obj);
      }
      com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse other = (com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse) obj;

      if (hasMsgSeq() != other.hasMsgSeq()) return false;
      if (hasMsgSeq()) {
        if (getMsgSeq()
            != other.getMsgSeq()) return false;
      }
      if (hasErrorCode() != other.hasErrorCode()) return false;
      if (hasErrorCode()) {
        if (!getErrorCode()
            .equals(other.getErrorCode())) return false;
      }
      if (hasErrorMessage() != other.hasErrorMessage()) return false;
      if (hasErrorMessage()) {
        if (!getErrorMessage()
            .equals(other.getErrorMessage())) return false;
      }
      if (hasMessageID() != other.hasMessageID()) return false;
      if (hasMessageID()) {
        if (!getMessageID()
            .equals(other.getMessageID())) return false;
      }
      if (hasReturnCode() != other.hasReturnCode()) return false;
      if (hasReturnCode()) {
        if (getReturnCode()
            != other.getReturnCode()) return false;
      }
      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasFullname() != other.hasFullname()) return false;
      if (hasFullname()) {
        if (!getFullname()
            .equals(other.getFullname())) return false;
      }
      if (!getAccountBalanceInfoList()
          .equals(other.getAccountBalanceInfoList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMsgSeq()) {
        hash = (37 * hash) + MSGSEQ_FIELD_NUMBER;
        hash = (53 * hash) + getMsgSeq();
      }
      if (hasErrorCode()) {
        hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
        hash = (53 * hash) + getErrorCode().hashCode();
      }
      if (hasErrorMessage()) {
        hash = (37 * hash) + ERRORMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getErrorMessage().hashCode();
      }
      if (hasMessageID()) {
        hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
        hash = (53 * hash) + getMessageID().hashCode();
      }
      if (hasReturnCode()) {
        hash = (37 * hash) + RETURNCODE_FIELD_NUMBER;
        hash = (53 * hash) + getReturnCode();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasFullname()) {
        hash = (37 * hash) + FULLNAME_FIELD_NUMBER;
        hash = (53 * hash) + getFullname().hashCode();
      }
      if (getAccountBalanceInfoCount() > 0) {
        hash = (37 * hash) + ACCOUNTBALANCEINFO_FIELD_NUMBER;
        hash = (53 * hash) + getAccountBalanceInfoList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.response.QueryClientCashBalanceResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.response.QueryClientCashBalanceResponse)
        com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.internal_static_protobuf_response_QueryClientCashBalanceResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.internal_static_protobuf_response_QueryClientCashBalanceResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse.class, com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse.Builder.class);
      }

      // Construct using com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAccountBalanceInfoFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        msgSeq_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        errorCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        errorMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        messageID_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        returnCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        fullname_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        if (accountBalanceInfoBuilder_ == null) {
          accountBalanceInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
        } else {
          accountBalanceInfoBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.internal_static_protobuf_response_QueryClientCashBalanceResponse_descriptor;
      }

      @java.lang.Override
      public com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse getDefaultInstanceForType() {
        return com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse build() {
        com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse buildPartial() {
        com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse result = new com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.msgSeq_ = msgSeq_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errorCode_ = errorCode_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.errorMessage_ = errorMessage_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.messageID_ = messageID_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.returnCode_ = returnCode_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          to_bitField0_ |= 0x00000040;
        }
        result.fullname_ = fullname_;
        if (accountBalanceInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000080) != 0)) {
            accountBalanceInfo_ = java.util.Collections.unmodifiableList(accountBalanceInfo_);
            bitField0_ = (bitField0_ & ~0x00000080);
          }
          result.accountBalanceInfo_ = accountBalanceInfo_;
        } else {
          result.accountBalanceInfo_ = accountBalanceInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse) {
          return mergeFrom((com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse other) {
        if (other == com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse.getDefaultInstance()) return this;
        if (other.hasMsgSeq()) {
          setMsgSeq(other.getMsgSeq());
        }
        if (other.hasErrorCode()) {
          bitField0_ |= 0x00000002;
          errorCode_ = other.errorCode_;
          onChanged();
        }
        if (other.hasErrorMessage()) {
          bitField0_ |= 0x00000004;
          errorMessage_ = other.errorMessage_;
          onChanged();
        }
        if (other.hasMessageID()) {
          bitField0_ |= 0x00000008;
          messageID_ = other.messageID_;
          onChanged();
        }
        if (other.hasReturnCode()) {
          setReturnCode(other.getReturnCode());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000020;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasFullname()) {
          bitField0_ |= 0x00000040;
          fullname_ = other.fullname_;
          onChanged();
        }
        if (accountBalanceInfoBuilder_ == null) {
          if (!other.accountBalanceInfo_.isEmpty()) {
            if (accountBalanceInfo_.isEmpty()) {
              accountBalanceInfo_ = other.accountBalanceInfo_;
              bitField0_ = (bitField0_ & ~0x00000080);
            } else {
              ensureAccountBalanceInfoIsMutable();
              accountBalanceInfo_.addAll(other.accountBalanceInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.accountBalanceInfo_.isEmpty()) {
            if (accountBalanceInfoBuilder_.isEmpty()) {
              accountBalanceInfoBuilder_.dispose();
              accountBalanceInfoBuilder_ = null;
              accountBalanceInfo_ = other.accountBalanceInfo_;
              bitField0_ = (bitField0_ & ~0x00000080);
              accountBalanceInfoBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAccountBalanceInfoFieldBuilder() : null;
            } else {
              accountBalanceInfoBuilder_.addAllMessages(other.accountBalanceInfo_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int msgSeq_ ;
      /**
       * <code>optional int32 msgSeq = 1;</code>
       */
      public boolean hasMsgSeq() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 msgSeq = 1;</code>
       */
      public int getMsgSeq() {
        return msgSeq_;
      }
      /**
       * <code>optional int32 msgSeq = 1;</code>
       */
      public Builder setMsgSeq(int value) {
        bitField0_ |= 0x00000001;
        msgSeq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 msgSeq = 1;</code>
       */
      public Builder clearMsgSeq() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgSeq_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object errorCode_ = "";
      /**
       * <code>optional string errorCode = 2;</code>
       */
      public boolean hasErrorCode() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string errorCode = 2;</code>
       */
      public java.lang.String getErrorCode() {
        java.lang.Object ref = errorCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errorCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string errorCode = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrorCodeBytes() {
        java.lang.Object ref = errorCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errorCode = 2;</code>
       */
      public Builder setErrorCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorCode = 2;</code>
       */
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errorCode_ = getDefaultInstance().getErrorCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorCode = 2;</code>
       */
      public Builder setErrorCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errorCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object errorMessage_ = "";
      /**
       * <code>optional string errorMessage = 3;</code>
       */
      public boolean hasErrorMessage() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string errorMessage = 3;</code>
       */
      public java.lang.String getErrorMessage() {
        java.lang.Object ref = errorMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errorMessage_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string errorMessage = 3;</code>
       */
      public com.google.protobuf.ByteString
          getErrorMessageBytes() {
        java.lang.Object ref = errorMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errorMessage = 3;</code>
       */
      public Builder setErrorMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        errorMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorMessage = 3;</code>
       */
      public Builder clearErrorMessage() {
        bitField0_ = (bitField0_ & ~0x00000004);
        errorMessage_ = getDefaultInstance().getErrorMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorMessage = 3;</code>
       */
      public Builder setErrorMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        errorMessage_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object messageID_ = "";
      /**
       * <code>optional string messageID = 4;</code>
       */
      public boolean hasMessageID() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string messageID = 4;</code>
       */
      public java.lang.String getMessageID() {
        java.lang.Object ref = messageID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            messageID_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string messageID = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMessageIDBytes() {
        java.lang.Object ref = messageID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string messageID = 4;</code>
       */
      public Builder setMessageID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        messageID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string messageID = 4;</code>
       */
      public Builder clearMessageID() {
        bitField0_ = (bitField0_ & ~0x00000008);
        messageID_ = getDefaultInstance().getMessageID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string messageID = 4;</code>
       */
      public Builder setMessageIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        messageID_ = value;
        onChanged();
        return this;
      }

      private int returnCode_ ;
      /**
       * <code>optional int32 returnCode = 5;</code>
       */
      public boolean hasReturnCode() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional int32 returnCode = 5;</code>
       */
      public int getReturnCode() {
        return returnCode_;
      }
      /**
       * <code>optional int32 returnCode = 5;</code>
       */
      public Builder setReturnCode(int value) {
        bitField0_ |= 0x00000010;
        returnCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 returnCode = 5;</code>
       */
      public Builder clearReturnCode() {
        bitField0_ = (bitField0_ & ~0x00000010);
        returnCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 6;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional string name = 6;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 6;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 6;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 6;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000020);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 6;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object fullname_ = "";
      /**
       * <code>optional string fullname = 7;</code>
       */
      public boolean hasFullname() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional string fullname = 7;</code>
       */
      public java.lang.String getFullname() {
        java.lang.Object ref = fullname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fullname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string fullname = 7;</code>
       */
      public com.google.protobuf.ByteString
          getFullnameBytes() {
        java.lang.Object ref = fullname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fullname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string fullname = 7;</code>
       */
      public Builder setFullname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        fullname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string fullname = 7;</code>
       */
      public Builder clearFullname() {
        bitField0_ = (bitField0_ & ~0x00000040);
        fullname_ = getDefaultInstance().getFullname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string fullname = 7;</code>
       */
      public Builder setFullnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        fullname_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalance> accountBalanceInfo_ =
        java.util.Collections.emptyList();
      private void ensureAccountBalanceInfoIsMutable() {
        if (!((bitField0_ & 0x00000080) != 0)) {
          accountBalanceInfo_ = new java.util.ArrayList<com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalance>(accountBalanceInfo_);
          bitField0_ |= 0x00000080;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalance, com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalance.Builder, com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalanceOrBuilder> accountBalanceInfoBuilder_;

      /**
       * <code>repeated .protobuf.bean.AccountBalance accountBalanceInfo = 8;</code>
       */
      public java.util.List<com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalance> getAccountBalanceInfoList() {
        if (accountBalanceInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(accountBalanceInfo_);
        } else {
          return accountBalanceInfoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.bean.AccountBalance accountBalanceInfo = 8;</code>
       */
      public int getAccountBalanceInfoCount() {
        if (accountBalanceInfoBuilder_ == null) {
          return accountBalanceInfo_.size();
        } else {
          return accountBalanceInfoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.bean.AccountBalance accountBalanceInfo = 8;</code>
       */
      public com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalance getAccountBalanceInfo(int index) {
        if (accountBalanceInfoBuilder_ == null) {
          return accountBalanceInfo_.get(index);
        } else {
          return accountBalanceInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.bean.AccountBalance accountBalanceInfo = 8;</code>
       */
      public Builder setAccountBalanceInfo(
          int index, com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalance value) {
        if (accountBalanceInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAccountBalanceInfoIsMutable();
          accountBalanceInfo_.set(index, value);
          onChanged();
        } else {
          accountBalanceInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.bean.AccountBalance accountBalanceInfo = 8;</code>
       */
      public Builder setAccountBalanceInfo(
          int index, com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalance.Builder builderForValue) {
        if (accountBalanceInfoBuilder_ == null) {
          ensureAccountBalanceInfoIsMutable();
          accountBalanceInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          accountBalanceInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.bean.AccountBalance accountBalanceInfo = 8;</code>
       */
      public Builder addAccountBalanceInfo(com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalance value) {
        if (accountBalanceInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAccountBalanceInfoIsMutable();
          accountBalanceInfo_.add(value);
          onChanged();
        } else {
          accountBalanceInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.bean.AccountBalance accountBalanceInfo = 8;</code>
       */
      public Builder addAccountBalanceInfo(
          int index, com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalance value) {
        if (accountBalanceInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAccountBalanceInfoIsMutable();
          accountBalanceInfo_.add(index, value);
          onChanged();
        } else {
          accountBalanceInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.bean.AccountBalance accountBalanceInfo = 8;</code>
       */
      public Builder addAccountBalanceInfo(
          com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalance.Builder builderForValue) {
        if (accountBalanceInfoBuilder_ == null) {
          ensureAccountBalanceInfoIsMutable();
          accountBalanceInfo_.add(builderForValue.build());
          onChanged();
        } else {
          accountBalanceInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.bean.AccountBalance accountBalanceInfo = 8;</code>
       */
      public Builder addAccountBalanceInfo(
          int index, com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalance.Builder builderForValue) {
        if (accountBalanceInfoBuilder_ == null) {
          ensureAccountBalanceInfoIsMutable();
          accountBalanceInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          accountBalanceInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.bean.AccountBalance accountBalanceInfo = 8;</code>
       */
      public Builder addAllAccountBalanceInfo(
          java.lang.Iterable<? extends com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalance> values) {
        if (accountBalanceInfoBuilder_ == null) {
          ensureAccountBalanceInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, accountBalanceInfo_);
          onChanged();
        } else {
          accountBalanceInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.bean.AccountBalance accountBalanceInfo = 8;</code>
       */
      public Builder clearAccountBalanceInfo() {
        if (accountBalanceInfoBuilder_ == null) {
          accountBalanceInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
          onChanged();
        } else {
          accountBalanceInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.bean.AccountBalance accountBalanceInfo = 8;</code>
       */
      public Builder removeAccountBalanceInfo(int index) {
        if (accountBalanceInfoBuilder_ == null) {
          ensureAccountBalanceInfoIsMutable();
          accountBalanceInfo_.remove(index);
          onChanged();
        } else {
          accountBalanceInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.bean.AccountBalance accountBalanceInfo = 8;</code>
       */
      public com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalance.Builder getAccountBalanceInfoBuilder(
          int index) {
        return getAccountBalanceInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.bean.AccountBalance accountBalanceInfo = 8;</code>
       */
      public com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalanceOrBuilder getAccountBalanceInfoOrBuilder(
          int index) {
        if (accountBalanceInfoBuilder_ == null) {
          return accountBalanceInfo_.get(index);  } else {
          return accountBalanceInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.bean.AccountBalance accountBalanceInfo = 8;</code>
       */
      public java.util.List<? extends com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalanceOrBuilder> 
           getAccountBalanceInfoOrBuilderList() {
        if (accountBalanceInfoBuilder_ != null) {
          return accountBalanceInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(accountBalanceInfo_);
        }
      }
      /**
       * <code>repeated .protobuf.bean.AccountBalance accountBalanceInfo = 8;</code>
       */
      public com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalance.Builder addAccountBalanceInfoBuilder() {
        return getAccountBalanceInfoFieldBuilder().addBuilder(
            com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalance.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.bean.AccountBalance accountBalanceInfo = 8;</code>
       */
      public com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalance.Builder addAccountBalanceInfoBuilder(
          int index) {
        return getAccountBalanceInfoFieldBuilder().addBuilder(
            index, com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalance.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.bean.AccountBalance accountBalanceInfo = 8;</code>
       */
      public java.util.List<com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalance.Builder> 
           getAccountBalanceInfoBuilderList() {
        return getAccountBalanceInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalance, com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalance.Builder, com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalanceOrBuilder> 
          getAccountBalanceInfoFieldBuilder() {
        if (accountBalanceInfoBuilder_ == null) {
          accountBalanceInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalance, com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalance.Builder, com.txtech.services.protobuf.bean.AccountBalanceProtos.AccountBalanceOrBuilder>(
                  accountBalanceInfo_,
                  ((bitField0_ & 0x00000080) != 0),
                  getParentForChildren(),
                  isClean());
          accountBalanceInfo_ = null;
        }
        return accountBalanceInfoBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.response.QueryClientCashBalanceResponse)
    }

    // @@protoc_insertion_point(class_scope:protobuf.response.QueryClientCashBalanceResponse)
    private static final com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse();
    }

    public static com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<QueryClientCashBalanceResponse>
        PARSER = new com.google.protobuf.AbstractParser<QueryClientCashBalanceResponse>() {
      @java.lang.Override
      public QueryClientCashBalanceResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueryClientCashBalanceResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QueryClientCashBalanceResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueryClientCashBalanceResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.txtech.services.protobuf.response.QueryClientCashBalanceResponseProtos.QueryClientCashBalanceResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_response_QueryClientCashBalanceResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_response_QueryClientCashBalanceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n6protobuf/response/queryClientCashBalan" +
      "ceResponse.proto\022\021protobuf.response\032\"pro" +
      "tobuf/bean/accountBalance.proto\"\333\001\n\036Quer" +
      "yClientCashBalanceResponse\022\016\n\006msgSeq\030\001 \001" +
      "(\005\022\021\n\terrorCode\030\002 \001(\t\022\024\n\014errorMessage\030\003 " +
      "\001(\t\022\021\n\tmessageID\030\004 \001(\t\022\022\n\nreturnCode\030\005 \001" +
      "(\005\022\014\n\004name\030\006 \001(\t\022\020\n\010fullname\030\007 \001(\t\0229\n\022ac" +
      "countBalanceInfo\030\010 \003(\0132\035.protobuf.bean.A" +
      "ccountBalanceBM\n%com.txtech.services.pro" +
      "tobuf.responseB$QueryClientCashBalanceRe" +
      "sponseProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.txtech.services.protobuf.bean.AccountBalanceProtos.getDescriptor(),
        }, assigner);
    internal_static_protobuf_response_QueryClientCashBalanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_response_QueryClientCashBalanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_response_QueryClientCashBalanceResponse_descriptor,
        new java.lang.String[] { "MsgSeq", "ErrorCode", "ErrorMessage", "MessageID", "ReturnCode", "Name", "Fullname", "AccountBalanceInfo", });
    com.txtech.services.protobuf.bean.AccountBalanceProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
