// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/response/RecoveryDNMsgResp.proto

package com.txtech.services.protobuf.response;

public final class RecoveryDNMsgProtoResp {
  private RecoveryDNMsgProtoResp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RecoveryDNMsgRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.response.RecoveryDNMsgResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string errorCode = 1;</code>
     */
    boolean hasErrorCode();
    /**
     * <code>optional string errorCode = 1;</code>
     */
    java.lang.String getErrorCode();
    /**
     * <code>optional string errorCode = 1;</code>
     */
    com.google.protobuf.ByteString
        getErrorCodeBytes();

    /**
     * <code>optional string errorMessage = 2;</code>
     */
    boolean hasErrorMessage();
    /**
     * <code>optional string errorMessage = 2;</code>
     */
    java.lang.String getErrorMessage();
    /**
     * <code>optional string errorMessage = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrorMessageBytes();

    /**
     * <code>optional int32 rowCount = 3;</code>
     */
    boolean hasRowCount();
    /**
     * <code>optional int32 rowCount = 3;</code>
     */
    int getRowCount();

    /**
     * <code>optional int32 batchSize = 4;</code>
     */
    boolean hasBatchSize();
    /**
     * <code>optional int32 batchSize = 4;</code>
     */
    int getBatchSize();

    /**
     * <code>optional int32 batchNum = 5;</code>
     */
    boolean hasBatchNum();
    /**
     * <code>optional int32 batchNum = 5;</code>
     */
    int getBatchNum();

    /**
     * <code>optional int32 totalBatchCount = 6;</code>
     */
    boolean hasTotalBatchCount();
    /**
     * <code>optional int32 totalBatchCount = 6;</code>
     */
    int getTotalBatchCount();

    /**
     * <code>repeated .protobuf.bean.OrderEnqDetail mainResult = 7;</code>
     */
    java.util.List<com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetail> 
        getMainResultList();
    /**
     * <code>repeated .protobuf.bean.OrderEnqDetail mainResult = 7;</code>
     */
    com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetail getMainResult(int index);
    /**
     * <code>repeated .protobuf.bean.OrderEnqDetail mainResult = 7;</code>
     */
    int getMainResultCount();
    /**
     * <code>repeated .protobuf.bean.OrderEnqDetail mainResult = 7;</code>
     */
    java.util.List<? extends com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetailOrBuilder> 
        getMainResultOrBuilderList();
    /**
     * <code>repeated .protobuf.bean.OrderEnqDetail mainResult = 7;</code>
     */
    com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetailOrBuilder getMainResultOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protobuf.response.RecoveryDNMsgResp}
   */
  public  static final class RecoveryDNMsgResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.response.RecoveryDNMsgResp)
      RecoveryDNMsgRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RecoveryDNMsgResp.newBuilder() to construct.
    private RecoveryDNMsgResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RecoveryDNMsgResp() {
      errorCode_ = "";
      errorMessage_ = "";
      mainResult_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RecoveryDNMsgResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              errorCode_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              errorMessage_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              rowCount_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              batchSize_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              batchNum_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              totalBatchCount_ = input.readInt32();
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) != 0)) {
                mainResult_ = new java.util.ArrayList<com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetail>();
                mutable_bitField0_ |= 0x00000040;
              }
              mainResult_.add(
                  input.readMessage(com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetail.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) != 0)) {
          mainResult_ = java.util.Collections.unmodifiableList(mainResult_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.internal_static_protobuf_response_RecoveryDNMsgResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.internal_static_protobuf_response_RecoveryDNMsgResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp.class, com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp.Builder.class);
    }

    private int bitField0_;
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object errorCode_;
    /**
     * <code>optional string errorCode = 1;</code>
     */
    public boolean hasErrorCode() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string errorCode = 1;</code>
     */
    public java.lang.String getErrorCode() {
      java.lang.Object ref = errorCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string errorCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getErrorCodeBytes() {
      java.lang.Object ref = errorCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRORMESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object errorMessage_;
    /**
     * <code>optional string errorMessage = 2;</code>
     */
    public boolean hasErrorMessage() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string errorMessage = 2;</code>
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorMessage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string errorMessage = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROWCOUNT_FIELD_NUMBER = 3;
    private int rowCount_;
    /**
     * <code>optional int32 rowCount = 3;</code>
     */
    public boolean hasRowCount() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 rowCount = 3;</code>
     */
    public int getRowCount() {
      return rowCount_;
    }

    public static final int BATCHSIZE_FIELD_NUMBER = 4;
    private int batchSize_;
    /**
     * <code>optional int32 batchSize = 4;</code>
     */
    public boolean hasBatchSize() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 batchSize = 4;</code>
     */
    public int getBatchSize() {
      return batchSize_;
    }

    public static final int BATCHNUM_FIELD_NUMBER = 5;
    private int batchNum_;
    /**
     * <code>optional int32 batchNum = 5;</code>
     */
    public boolean hasBatchNum() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 batchNum = 5;</code>
     */
    public int getBatchNum() {
      return batchNum_;
    }

    public static final int TOTALBATCHCOUNT_FIELD_NUMBER = 6;
    private int totalBatchCount_;
    /**
     * <code>optional int32 totalBatchCount = 6;</code>
     */
    public boolean hasTotalBatchCount() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional int32 totalBatchCount = 6;</code>
     */
    public int getTotalBatchCount() {
      return totalBatchCount_;
    }

    public static final int MAINRESULT_FIELD_NUMBER = 7;
    private java.util.List<com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetail> mainResult_;
    /**
     * <code>repeated .protobuf.bean.OrderEnqDetail mainResult = 7;</code>
     */
    public java.util.List<com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetail> getMainResultList() {
      return mainResult_;
    }
    /**
     * <code>repeated .protobuf.bean.OrderEnqDetail mainResult = 7;</code>
     */
    public java.util.List<? extends com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetailOrBuilder> 
        getMainResultOrBuilderList() {
      return mainResult_;
    }
    /**
     * <code>repeated .protobuf.bean.OrderEnqDetail mainResult = 7;</code>
     */
    public int getMainResultCount() {
      return mainResult_.size();
    }
    /**
     * <code>repeated .protobuf.bean.OrderEnqDetail mainResult = 7;</code>
     */
    public com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetail getMainResult(int index) {
      return mainResult_.get(index);
    }
    /**
     * <code>repeated .protobuf.bean.OrderEnqDetail mainResult = 7;</code>
     */
    public com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetailOrBuilder getMainResultOrBuilder(
        int index) {
      return mainResult_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, errorCode_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errorMessage_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, rowCount_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, batchSize_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(5, batchNum_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt32(6, totalBatchCount_);
      }
      for (int i = 0; i < mainResult_.size(); i++) {
        output.writeMessage(7, mainResult_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, errorCode_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errorMessage_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, rowCount_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, batchSize_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, batchNum_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, totalBatchCount_);
      }
      for (int i = 0; i < mainResult_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, mainResult_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp)) {
        return super.equals(obj);
      }
      com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp other = (com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp) obj;

      if (hasErrorCode() != other.hasErrorCode()) return false;
      if (hasErrorCode()) {
        if (!getErrorCode()
            .equals(other.getErrorCode())) return false;
      }
      if (hasErrorMessage() != other.hasErrorMessage()) return false;
      if (hasErrorMessage()) {
        if (!getErrorMessage()
            .equals(other.getErrorMessage())) return false;
      }
      if (hasRowCount() != other.hasRowCount()) return false;
      if (hasRowCount()) {
        if (getRowCount()
            != other.getRowCount()) return false;
      }
      if (hasBatchSize() != other.hasBatchSize()) return false;
      if (hasBatchSize()) {
        if (getBatchSize()
            != other.getBatchSize()) return false;
      }
      if (hasBatchNum() != other.hasBatchNum()) return false;
      if (hasBatchNum()) {
        if (getBatchNum()
            != other.getBatchNum()) return false;
      }
      if (hasTotalBatchCount() != other.hasTotalBatchCount()) return false;
      if (hasTotalBatchCount()) {
        if (getTotalBatchCount()
            != other.getTotalBatchCount()) return false;
      }
      if (!getMainResultList()
          .equals(other.getMainResultList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasErrorCode()) {
        hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
        hash = (53 * hash) + getErrorCode().hashCode();
      }
      if (hasErrorMessage()) {
        hash = (37 * hash) + ERRORMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getErrorMessage().hashCode();
      }
      if (hasRowCount()) {
        hash = (37 * hash) + ROWCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getRowCount();
      }
      if (hasBatchSize()) {
        hash = (37 * hash) + BATCHSIZE_FIELD_NUMBER;
        hash = (53 * hash) + getBatchSize();
      }
      if (hasBatchNum()) {
        hash = (37 * hash) + BATCHNUM_FIELD_NUMBER;
        hash = (53 * hash) + getBatchNum();
      }
      if (hasTotalBatchCount()) {
        hash = (37 * hash) + TOTALBATCHCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getTotalBatchCount();
      }
      if (getMainResultCount() > 0) {
        hash = (37 * hash) + MAINRESULT_FIELD_NUMBER;
        hash = (53 * hash) + getMainResultList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.response.RecoveryDNMsgResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.response.RecoveryDNMsgResp)
        com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.internal_static_protobuf_response_RecoveryDNMsgResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.internal_static_protobuf_response_RecoveryDNMsgResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp.class, com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp.Builder.class);
      }

      // Construct using com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMainResultFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        errorCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        errorMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        rowCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        batchSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        batchNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        totalBatchCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        if (mainResultBuilder_ == null) {
          mainResult_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          mainResultBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.internal_static_protobuf_response_RecoveryDNMsgResp_descriptor;
      }

      @java.lang.Override
      public com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp getDefaultInstanceForType() {
        return com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp.getDefaultInstance();
      }

      @java.lang.Override
      public com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp build() {
        com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp buildPartial() {
        com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp result = new com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.errorCode_ = errorCode_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errorMessage_ = errorMessage_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.rowCount_ = rowCount_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.batchSize_ = batchSize_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.batchNum_ = batchNum_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.totalBatchCount_ = totalBatchCount_;
          to_bitField0_ |= 0x00000020;
        }
        if (mainResultBuilder_ == null) {
          if (((bitField0_ & 0x00000040) != 0)) {
            mainResult_ = java.util.Collections.unmodifiableList(mainResult_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.mainResult_ = mainResult_;
        } else {
          result.mainResult_ = mainResultBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp) {
          return mergeFrom((com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp other) {
        if (other == com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp.getDefaultInstance()) return this;
        if (other.hasErrorCode()) {
          bitField0_ |= 0x00000001;
          errorCode_ = other.errorCode_;
          onChanged();
        }
        if (other.hasErrorMessage()) {
          bitField0_ |= 0x00000002;
          errorMessage_ = other.errorMessage_;
          onChanged();
        }
        if (other.hasRowCount()) {
          setRowCount(other.getRowCount());
        }
        if (other.hasBatchSize()) {
          setBatchSize(other.getBatchSize());
        }
        if (other.hasBatchNum()) {
          setBatchNum(other.getBatchNum());
        }
        if (other.hasTotalBatchCount()) {
          setTotalBatchCount(other.getTotalBatchCount());
        }
        if (mainResultBuilder_ == null) {
          if (!other.mainResult_.isEmpty()) {
            if (mainResult_.isEmpty()) {
              mainResult_ = other.mainResult_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureMainResultIsMutable();
              mainResult_.addAll(other.mainResult_);
            }
            onChanged();
          }
        } else {
          if (!other.mainResult_.isEmpty()) {
            if (mainResultBuilder_.isEmpty()) {
              mainResultBuilder_.dispose();
              mainResultBuilder_ = null;
              mainResult_ = other.mainResult_;
              bitField0_ = (bitField0_ & ~0x00000040);
              mainResultBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMainResultFieldBuilder() : null;
            } else {
              mainResultBuilder_.addAllMessages(other.mainResult_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object errorCode_ = "";
      /**
       * <code>optional string errorCode = 1;</code>
       */
      public boolean hasErrorCode() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string errorCode = 1;</code>
       */
      public java.lang.String getErrorCode() {
        java.lang.Object ref = errorCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errorCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string errorCode = 1;</code>
       */
      public com.google.protobuf.ByteString
          getErrorCodeBytes() {
        java.lang.Object ref = errorCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errorCode = 1;</code>
       */
      public Builder setErrorCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorCode = 1;</code>
       */
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errorCode_ = getDefaultInstance().getErrorCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorCode = 1;</code>
       */
      public Builder setErrorCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        errorCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object errorMessage_ = "";
      /**
       * <code>optional string errorMessage = 2;</code>
       */
      public boolean hasErrorMessage() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string errorMessage = 2;</code>
       */
      public java.lang.String getErrorMessage() {
        java.lang.Object ref = errorMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errorMessage_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string errorMessage = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrorMessageBytes() {
        java.lang.Object ref = errorMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errorMessage = 2;</code>
       */
      public Builder setErrorMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errorMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorMessage = 2;</code>
       */
      public Builder clearErrorMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errorMessage_ = getDefaultInstance().getErrorMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorMessage = 2;</code>
       */
      public Builder setErrorMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errorMessage_ = value;
        onChanged();
        return this;
      }

      private int rowCount_ ;
      /**
       * <code>optional int32 rowCount = 3;</code>
       */
      public boolean hasRowCount() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 rowCount = 3;</code>
       */
      public int getRowCount() {
        return rowCount_;
      }
      /**
       * <code>optional int32 rowCount = 3;</code>
       */
      public Builder setRowCount(int value) {
        bitField0_ |= 0x00000004;
        rowCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 rowCount = 3;</code>
       */
      public Builder clearRowCount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        rowCount_ = 0;
        onChanged();
        return this;
      }

      private int batchSize_ ;
      /**
       * <code>optional int32 batchSize = 4;</code>
       */
      public boolean hasBatchSize() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional int32 batchSize = 4;</code>
       */
      public int getBatchSize() {
        return batchSize_;
      }
      /**
       * <code>optional int32 batchSize = 4;</code>
       */
      public Builder setBatchSize(int value) {
        bitField0_ |= 0x00000008;
        batchSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 batchSize = 4;</code>
       */
      public Builder clearBatchSize() {
        bitField0_ = (bitField0_ & ~0x00000008);
        batchSize_ = 0;
        onChanged();
        return this;
      }

      private int batchNum_ ;
      /**
       * <code>optional int32 batchNum = 5;</code>
       */
      public boolean hasBatchNum() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional int32 batchNum = 5;</code>
       */
      public int getBatchNum() {
        return batchNum_;
      }
      /**
       * <code>optional int32 batchNum = 5;</code>
       */
      public Builder setBatchNum(int value) {
        bitField0_ |= 0x00000010;
        batchNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 batchNum = 5;</code>
       */
      public Builder clearBatchNum() {
        bitField0_ = (bitField0_ & ~0x00000010);
        batchNum_ = 0;
        onChanged();
        return this;
      }

      private int totalBatchCount_ ;
      /**
       * <code>optional int32 totalBatchCount = 6;</code>
       */
      public boolean hasTotalBatchCount() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional int32 totalBatchCount = 6;</code>
       */
      public int getTotalBatchCount() {
        return totalBatchCount_;
      }
      /**
       * <code>optional int32 totalBatchCount = 6;</code>
       */
      public Builder setTotalBatchCount(int value) {
        bitField0_ |= 0x00000020;
        totalBatchCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 totalBatchCount = 6;</code>
       */
      public Builder clearTotalBatchCount() {
        bitField0_ = (bitField0_ & ~0x00000020);
        totalBatchCount_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetail> mainResult_ =
        java.util.Collections.emptyList();
      private void ensureMainResultIsMutable() {
        if (!((bitField0_ & 0x00000040) != 0)) {
          mainResult_ = new java.util.ArrayList<com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetail>(mainResult_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetail, com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetail.Builder, com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetailOrBuilder> mainResultBuilder_;

      /**
       * <code>repeated .protobuf.bean.OrderEnqDetail mainResult = 7;</code>
       */
      public java.util.List<com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetail> getMainResultList() {
        if (mainResultBuilder_ == null) {
          return java.util.Collections.unmodifiableList(mainResult_);
        } else {
          return mainResultBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.bean.OrderEnqDetail mainResult = 7;</code>
       */
      public int getMainResultCount() {
        if (mainResultBuilder_ == null) {
          return mainResult_.size();
        } else {
          return mainResultBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.bean.OrderEnqDetail mainResult = 7;</code>
       */
      public com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetail getMainResult(int index) {
        if (mainResultBuilder_ == null) {
          return mainResult_.get(index);
        } else {
          return mainResultBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.bean.OrderEnqDetail mainResult = 7;</code>
       */
      public Builder setMainResult(
          int index, com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetail value) {
        if (mainResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMainResultIsMutable();
          mainResult_.set(index, value);
          onChanged();
        } else {
          mainResultBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.bean.OrderEnqDetail mainResult = 7;</code>
       */
      public Builder setMainResult(
          int index, com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetail.Builder builderForValue) {
        if (mainResultBuilder_ == null) {
          ensureMainResultIsMutable();
          mainResult_.set(index, builderForValue.build());
          onChanged();
        } else {
          mainResultBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.bean.OrderEnqDetail mainResult = 7;</code>
       */
      public Builder addMainResult(com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetail value) {
        if (mainResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMainResultIsMutable();
          mainResult_.add(value);
          onChanged();
        } else {
          mainResultBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.bean.OrderEnqDetail mainResult = 7;</code>
       */
      public Builder addMainResult(
          int index, com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetail value) {
        if (mainResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMainResultIsMutable();
          mainResult_.add(index, value);
          onChanged();
        } else {
          mainResultBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.bean.OrderEnqDetail mainResult = 7;</code>
       */
      public Builder addMainResult(
          com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetail.Builder builderForValue) {
        if (mainResultBuilder_ == null) {
          ensureMainResultIsMutable();
          mainResult_.add(builderForValue.build());
          onChanged();
        } else {
          mainResultBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.bean.OrderEnqDetail mainResult = 7;</code>
       */
      public Builder addMainResult(
          int index, com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetail.Builder builderForValue) {
        if (mainResultBuilder_ == null) {
          ensureMainResultIsMutable();
          mainResult_.add(index, builderForValue.build());
          onChanged();
        } else {
          mainResultBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.bean.OrderEnqDetail mainResult = 7;</code>
       */
      public Builder addAllMainResult(
          java.lang.Iterable<? extends com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetail> values) {
        if (mainResultBuilder_ == null) {
          ensureMainResultIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, mainResult_);
          onChanged();
        } else {
          mainResultBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.bean.OrderEnqDetail mainResult = 7;</code>
       */
      public Builder clearMainResult() {
        if (mainResultBuilder_ == null) {
          mainResult_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          mainResultBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.bean.OrderEnqDetail mainResult = 7;</code>
       */
      public Builder removeMainResult(int index) {
        if (mainResultBuilder_ == null) {
          ensureMainResultIsMutable();
          mainResult_.remove(index);
          onChanged();
        } else {
          mainResultBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.bean.OrderEnqDetail mainResult = 7;</code>
       */
      public com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetail.Builder getMainResultBuilder(
          int index) {
        return getMainResultFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.bean.OrderEnqDetail mainResult = 7;</code>
       */
      public com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetailOrBuilder getMainResultOrBuilder(
          int index) {
        if (mainResultBuilder_ == null) {
          return mainResult_.get(index);  } else {
          return mainResultBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.bean.OrderEnqDetail mainResult = 7;</code>
       */
      public java.util.List<? extends com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetailOrBuilder> 
           getMainResultOrBuilderList() {
        if (mainResultBuilder_ != null) {
          return mainResultBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(mainResult_);
        }
      }
      /**
       * <code>repeated .protobuf.bean.OrderEnqDetail mainResult = 7;</code>
       */
      public com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetail.Builder addMainResultBuilder() {
        return getMainResultFieldBuilder().addBuilder(
            com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.bean.OrderEnqDetail mainResult = 7;</code>
       */
      public com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetail.Builder addMainResultBuilder(
          int index) {
        return getMainResultFieldBuilder().addBuilder(
            index, com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.bean.OrderEnqDetail mainResult = 7;</code>
       */
      public java.util.List<com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetail.Builder> 
           getMainResultBuilderList() {
        return getMainResultFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetail, com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetail.Builder, com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetailOrBuilder> 
          getMainResultFieldBuilder() {
        if (mainResultBuilder_ == null) {
          mainResultBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetail, com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetail.Builder, com.txtech.services.protobuf.bean.OrderEnqDetailProtos.OrderEnqDetailOrBuilder>(
                  mainResult_,
                  ((bitField0_ & 0x00000040) != 0),
                  getParentForChildren(),
                  isClean());
          mainResult_ = null;
        }
        return mainResultBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.response.RecoveryDNMsgResp)
    }

    // @@protoc_insertion_point(class_scope:protobuf.response.RecoveryDNMsgResp)
    private static final com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp();
    }

    public static com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<RecoveryDNMsgResp>
        PARSER = new com.google.protobuf.AbstractParser<RecoveryDNMsgResp>() {
      @java.lang.Override
      public RecoveryDNMsgResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RecoveryDNMsgResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RecoveryDNMsgResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RecoveryDNMsgResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.txtech.services.protobuf.response.RecoveryDNMsgProtoResp.RecoveryDNMsgResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_response_RecoveryDNMsgResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_response_RecoveryDNMsgResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)protobuf/response/RecoveryDNMsgResp.pr" +
      "oto\022\021protobuf.response\032\"protobuf/bean/or" +
      "derEnqDetail.proto\"\277\001\n\021RecoveryDNMsgResp" +
      "\022\021\n\terrorCode\030\001 \001(\t\022\024\n\014errorMessage\030\002 \001(" +
      "\t\022\020\n\010rowCount\030\003 \001(\005\022\021\n\tbatchSize\030\004 \001(\005\022\020" +
      "\n\010batchNum\030\005 \001(\005\022\027\n\017totalBatchCount\030\006 \001(" +
      "\005\0221\n\nmainResult\030\007 \003(\0132\035.protobuf.bean.Or" +
      "derEnqDetailB?\n%com.txtech.services.prot" +
      "obuf.responseB\026RecoveryDNMsgProtoResp"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.txtech.services.protobuf.bean.OrderEnqDetailProtos.getDescriptor(),
        }, assigner);
    internal_static_protobuf_response_RecoveryDNMsgResp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_response_RecoveryDNMsgResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_response_RecoveryDNMsgResp_descriptor,
        new java.lang.String[] { "ErrorCode", "ErrorMessage", "RowCount", "BatchSize", "BatchNum", "TotalBatchCount", "MainResult", });
    com.txtech.services.protobuf.bean.OrderEnqDetailProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
